# render.yaml — Render Blueprint for full-stack (Node + React/Vite)
# Place this file in the ROOT of your repo (same level as /server and /client)

services:
  # ----------------- Backend Service (Express + MongoDB) -----------------
  - type: web
    name: freelanceflow-backend
    runtime: node
    rootDir: server
    buildCommand: "npm ci"
    startCommand: "npm start"
    healthCheckPath: "/api/__health"
    envVars:
      # Secrets to set manually later in Render dashboard
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      # Automatically inject frontend URL for CORS
      - key: FRONTEND_URL
        fromService:
          name: freelanceflow-frontend
          type: web
          envVarKey: RENDER_EXTERNAL_URL

  # ----------------- Frontend Service (Vite/React static site) -----------------
  - type: web
    name: freelanceflow-frontend
    runtime: static
    rootDir: client
    buildCommand: "npm ci && npm run build"
    staticPublishPath: "dist"
    envVars:
      # Automatically inject backend API URL into Vite build
      - key: VITE_API_URL
        fromService:
          name: freelanceflow-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
