services:
  - type: web
    name: freelanceflow-backend
    env: node
    rootDir: server
    buildCommand: "npm ci"
    startCommand: "npm start"
    healthCheckPath: "/api/__health"
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      # FRONTEND_URL points to the Static Site URL after it's created
      - key: FRONTEND_URL
        fromService:
          name: freelanceflow-frontend
          type: static_site
          property: url
      # Secrets you will fill in Render dashboard after the blueprint creates the service:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: static_site
    name: freelanceflow-frontend
    rootDir: client
    buildCommand: "npm ci && npm run build"
    staticPublishPath: "dist"
    plan: free
    autoDeploy: true
    envVars:
      # Vite frontend reads the backend URL at build time
      - key: VITE_API_URL
        fromService:
          name: freelanceflow-backend
          type: web
          property: url
